# `app.yaml` specifies your Python application's runtime configuration
# including versioning, URL routing, static file serving, etc.
#
# See https://developers.google.com/appengine/docs/python/config/appconfig.
#

# Replace with the Project ID from cloud.google.com/console.
application: your-cloud-project-id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Handlers define how to route requests for application.
handlers:
# Route requests to `/favicon.ico` and `/robots.txt`
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# Route all requests to `/static` to serve files contained in the
# `static` directory.
- url: /static
  static_dir: static

# Route all other requests to `main.bottle` WSGI application.
# The value for the script attribute has the following the format:
# `<path.to.module>.<wsgi_application>`
# Where `<wsgi_application>` is global WSGI application
# defined in `path.to.module` python module.
- url: .*  # This regex directs all routes to main.app
  script: main.bottle
# Require that the client is logged in.
  login: required